export const environment = {
  production: true,
  globalVar1: 200,
  globalVar2: 201,
  PONISTI: true,
  tselind: 0,
  tscrollpos: 0,
  tidstud: -1,
  noviidstud: -1,
  trowind: -1,
  prethscrollpos: 0,
  prethrowind: -1,
  NOVI: false,
  tlogged: true,
  emit_to_page: '',
  DEMO: false,
  tIMEMDB: 'AdcUniversity',
  tSlikeDir: 'UploadedImages',
  tSlikaFile: 'Photo000.jpg',
  YES: false,
  moji_data: {},
  HTTP_ANSWER: 0,
  err_message: '',
  DIALOGZATVOREN: false,
  tscrollposition_top: 0,
  gtstind: '0',
  gtendind: '16',
  toffset: 0,
  tsearchstring: '',
  THOST: 'www.adacco.com'
};

